### ISSUE TITLE
Crash whenever I type `style` on component?

### ISSUE THREAD

**Issue by Tj3n** [Intellicode/eslint-plugin-react-native#282]
Hi, I'm not sure what's wrong with my setup ( is quite default from Ignite ) but I'm getting crash whenever I try to type `style` in any components, doesn't matter what is it. Remove this from `extends` then it stop but also stopping inline style checking.
Thanks in advance!

Here's the log:
```
[Error - 10:27:12 PM] ESLint stack trace:
[Error - 10:27:12 PM] TypeError: Cannot read property 'expression' of null
Occurred while linting C:\Users\app\screens\cook-details\cook-details-info.tsx:22
    at JSXAttribute (C:\Users\node_modules\eslint-plugin-react-native\lib\rules\no-single-element-style-arrays.js:40:24)
    at C:\Users\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (C:\Users\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\Users\node_modules\eslint\lib\linter\node-event-generator.js:256:26)
    at NodeEventGenerator.applySelectors (C:\Users\node_modules\eslint\lib\linter\node-event-generator.js:285:22)
    at NodeEventGenerator.enterNode (C:\Users\node_modules\eslint\lib\linter\node-event-generator.js:299:14)
    at CodePathAnalyzer.enterNode (C:\Users\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:711:23)
    at C:Users\node_modules\eslint\lib\linter\linter.js:954:32
    at Array.forEach (<anonymous>)
```

Here's my eslint config:
```
"eslintConfig": {
    "root": true,
    "parser": "@typescript-eslint/parser",
    "extends": [
      "eslint:recommended",
      "plugin:@typescript-eslint/eslint-recommended",
      "plugin:@typescript-eslint/recommended",
      "plugin:react/recommended",
      "plugin:react-native/all",
      "standard",
      "prettier"
    ],
    "plugins": [
      "@typescript-eslint",
      "react",
      "react-native",
      "prettier"
    ],
    "parserOptions": {
      "ecmaFeatures": {
        "jsx": true
      },
      "project": "./tsconfig.json"
    },
    "settings": {
      "react": {
        "pragma": "React",
        "version": "detect"
      }
    },
    "globals": {
      "__DEV__": false,
      "jasmine": false,
      "beforeAll": false,
      "afterAll": false,
      "beforeEach": false,
      "afterEach": false,
      "test": false,
      "expect": false,
      "describe": false,
      "jest": false,
      "it": false
    },
    "rules": {
      "@typescript-eslint/ban-ts-ignore": 0,
      "@typescript-eslint/explicit-function-return-type": 0,
      "@typescript-eslint/explicit-member-accessibility": 0,
      "@typescript-eslint/explicit-module-boundary-types": 0,
      "@typescript-eslint/indent": 0,
      "@typescript-eslint/member-delimiter-style": 0,
      "@typescript-eslint/no-empty-interface": 0,
      "@typescript-eslint/no-explicit-any": 0,
      "@typescript-eslint/no-object-literal-type-assertion": 0,
      "@typescript-eslint/no-var-requires": 0,
      "comma-dangle": 0,
      "multiline-ternary": 0,
      "no-undef": 0,
      "no-unused-vars": 0,
      "no-use-before-define": "off",
      "quotes": 0,
      "react-native/no-raw-text": 0,
      "react/no-unescaped-entities": 0,
      "react/prop-types": "off",
      "space-before-function-paren": 0,
      "@typescript-eslint/no-extra-semi": 0,
      "generator-star-spacing": "off",
      "yield-star-spacing": "off",
      "template-curly-spacing": "off",
      "indent": "off"
    }
```

**Comment by AlanSl** [comment]
See https://github.com/Intellicode/eslint-plugin-react-native/issues/278

**Comment by Intellicode** [comment]
Should be fixed as discussed in #278

**Comment by Tj3n** [comment]
@AlanSl @Intellicode The fix in #278 doesn't fix this issue, I still have to add `"react-native/no-single-element-style-arrays": 0` to makes it stop crashing, just typed `style` then it crash instantly without any `="something"` or the sort. I'm using v3.11.0.
